[features]
seeds = false

[programs.devnet]
dapp = "FhXTLh3dbnDFFqRKQxh4vuWKQpMk9CNtZ8EWyWNyjSAw"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/ktitaro/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
