[package]
name = "dapp"
version = "0.1.0"
edition = "2021"

[lib]
name = "dapp"
crate-type = ["cdylib", "lib"]

[features]
no-idl = []
default = []
no-entrypoint = []
no-log-ix-name = []
cpi = ["no-entrypoint"]

[dependencies]
anchor-lang = "0.24.2"
